In [1]:
import requests
import matplotlib.pyplot as plt
import pandas as pd
import datetime
import numpy as np

In [8]:
#def get_social(symbol):
     # Get Into The social blockchain data from CryptoCompare API
    #url = "https://min-api.cryptocompare.com/data/social/coin/histo/hour?api_key=015b242e7bed3700ca69182009d5c7af87bf6b83f7c5a0e12eb5a9b01bee3fb0&limit=2000&fsym=" + symbol
    #data = requests.get(url).json()["Data"]["Data"]
    #df = pd.DataFrame(data)
    
    # Get pricing data from CryptoCompare API
    #price_url = 'https://min-api.cryptocompare.com/data/v2/histoday?tsym=USD&limit=2000&api_key=015b242e7bed3700ca69182009d5c7af87bf6b83f7c5a0e12eb5a9b01bee3fb0&fsym=' + symbol
    #histo_data = requests.get(price_url).json()["Data"]["Data"]
    
    #df_price = pd.DataFrame(histo_data)
    
    #combined = df.set_index('time').join(df_price.set_index('time'), on='time')
    
    #return combined

In [39]:
def get_social(symbol):
    url = "https://min-api.cryptocompare.com/data/social/coin/histo/hour?api_key=015b242e7bed3700ca69182009d5c7af87bf6b83f7c5a0e12eb5a9b01bee3fb0&limit=2000&fsym=" + symbol
    data = requests.get(url).json()[('Data')]
    df = pd.DataFrame(data)
    
    price_url = 'https://min-api.cryptocompare.com/data/v2/histohour?tsym=USD&limit=2000&api_key=015b242e7bed3700ca69182009d5c7af87bf6b83f7c5a0e12eb5a9b01bee3fb0&fsym=' + symbol
    histo_data = requests.get(price_url).json()["Data"]["Data"]
    
    df_price = pd.DataFrame(histo_data)
    
    combined = df.set_index('time').join(df_price.set_index('time'), on='time')
    return combined

In [40]:
df = get_social('BTC')

In [41]:
df.head()

,analysis_page_views,charts_page_views,code_repo_closed_issues,code_repo_closed_pull_issues,code_repo_contributors,code_repo_forks,code_repo_open_issues,code_repo_open_pull_issues,code_repo_stars,code_repo_subscribers,...,twitter_lists,twitter_statuses,close,conversionSymbol,conversionType,high,low,open,volumefrom,volumeto
time,,,,,,,,,,,,,,,,,,,,,
1589976000,1085212,9322614,0,12906,863,25769,495,383,43463,3496,...,6631,20316,9763.33,,direct,9778.53,9717.78,9720.55,1236.60,1.205975e+07
1589979600,1085216,9322775,4941,12910,863,25772,495,379,43466,3495,...,6631,20316,9782.17,,direct,9788.11,9745.34,9763.33,1192.39,1.165111e+07
1589983200,1085233,9322924,4941,12910,863,25772,495,379,43466,3495,...,6631,20316,9768.96,,direct,9795.03,9763.66,9782.17,1311.93,1.282341e+07
1589986800,1085246,9323051,0,12910,863,25773,495,379,43469,3495,...,6631,20316,9406.28,,direct,9768.96,9323.82,9768.96,17985.94,1.712904e+08
1589990400,1085259,9323333,0,12910,863,25773,495,379,43469,3495,...,6631,20316,9487.06,,direct,9516.32,9349.46,9406.28,7633.53,7.221004e+07

In [42]:
df.columns

Index(['analysis_page_views', 'charts_page_views', 'code_repo_closed_issues',
       'code_repo_closed_pull_issues', 'code_repo_contributors',
       'code_repo_forks', 'code_repo_open_issues',
       'code_repo_open_pull_issues', 'code_repo_stars',
       'code_repo_subscribers', 'comments', 'fb_likes', 'fb_talking_about',
       'followers', 'forum_page_views', 'influence_page_views',
       'markets_page_views', 'overview_page_views', 'points', 'posts',
       'reddit_active_users', 'reddit_comments_per_day',
       'reddit_comments_per_hour', 'reddit_posts_per_day',
       'reddit_posts_per_hour', 'reddit_subscribers', 'total_page_views',
       'trades_page_views', 'twitter_favourites', 'twitter_followers',
       'twitter_following', 'twitter_lists', 'twitter_statuses', 'close',
       'conversionSymbol', 'conversionType', 'high', 'low', 'open',
       'volumefrom', 'volumeto'],
      dtype='object')

In [43]:
df.reset_index(inplace = True)

In [44]:
df['time'] = pd.to_datetime(df['time'], unit = 's')
df.head(2)

,time,analysis_page_views,charts_page_views,code_repo_closed_issues,code_repo_closed_pull_issues,code_repo_contributors,code_repo_forks,code_repo_open_issues,code_repo_open_pull_issues,code_repo_stars,...,twitter_lists,twitter_statuses,close,conversionSymbol,conversionType,high,low,open,volumefrom,volumeto
0,2020-05-20 12:00:00,1085212,9322614,0,12906,863,25769,495,383,43463,...,6631,20316,9763.33,,direct,9778.53,9717.78,9720.55,1236.60,12059747.00
1,2020-05-20 13:00:00,1085216,9322775,4941,12910,863,25772,495,379,43466,...,6631,20316,9782.17,,direct,9788.11,9745.34,9763.33,1192.39,11651111.87

In [45]:
df.set_index("time", drop=True, inplace=True)
df.head(2)

,analysis_page_views,charts_page_views,code_repo_closed_issues,code_repo_closed_pull_issues,code_repo_contributors,code_repo_forks,code_repo_open_issues,code_repo_open_pull_issues,code_repo_stars,code_repo_subscribers,...,twitter_lists,twitter_statuses,close,conversionSymbol,conversionType,high,low,open,volumefrom,volumeto
time,,,,,,,,,,,,,,,,,,,,,
2020-05-20 12:00:00,1085212,9322614,0,12906,863,25769,495,383,43463,3496,...,6631,20316,9763.33,,direct,9778.53,9717.78,9720.55,1236.60,12059747.00
2020-05-20 13:00:00,1085216,9322775,4941,12910,863,25772,495,379,43466,3495,...,6631,20316,9782.17,,direct,9788.11,9745.34,9763.33,1192.39,11651111.87

In [46]:
df.tail(2)

,analysis_page_views,charts_page_views,code_repo_closed_issues,code_repo_closed_pull_issues,code_repo_contributors,code_repo_forks,code_repo_open_issues,code_repo_open_pull_issues,code_repo_stars,code_repo_subscribers,...,twitter_lists,twitter_statuses,close,conversionSymbol,conversionType,high,low,open,volumefrom,volumeto
time,,,,,,,,,,,,,,,,,,,,,
2020-08-11 19:00:00,1097229,9487053,5071,13381,897,26183,541,390,44525,3509,...,6631,20316,11395.60,,direct,11485.05,11389.84,11448.88,2587.22,29553803.56
2020-08-11 20:00:00,1097238,9487163,5072,13381,897,26183,541,390,44525,3509,...,6631,20316,11257.85,,direct,11395.66,11214.39,11395.60,2894.90,32686776.38

In [47]:
df.dtypes

analysis_page_views               int64
charts_page_views                 int64
code_repo_closed_issues           int64
code_repo_closed_pull_issues      int64
code_repo_contributors            int64
code_repo_forks                   int64
code_repo_open_issues             int64
code_repo_open_pull_issues        int64
code_repo_stars                   int64
code_repo_subscribers             int64
comments                          int64
fb_likes                          int64
fb_talking_about                  int64
followers                         int64
forum_page_views                  int64
influence_page_views              int64
markets_page_views                int64
overview_page_views               int64
points                            int64
posts                             int64
reddit_active_users               int64
reddit_comments_per_day         float64
reddit_comments_per_hour        float64
reddit_posts_per_day            float64
reddit_posts_per_hour           float64
reddit_subscribers                int64
total_page_views                  int64
trades_page_views                 int64
twitter_favourites                int64
twitter_followers                 int64
twitter_following                 int64
twitter_lists                     int64
twitter_statuses                  int64
close                           float64
conversionSymbol                 object
conversionType                   object
high                            float64
low                             float64
open                            float64
volumefrom                      float64
volumeto                        float64
dtype: object

In [49]:
df.drop(columns=['high', 'low', 'open', 'volumefrom', 'volumeto', 'conversionType', 'conversionSymbol'], inplace = True)

In [51]:
df['returns']= df['close'].pct_change()

In [52]:
social_df = df.drop(columns=['close'])

In [54]:
social_df['analysis_page_views'].isnull()

time
2020-05-20 12:00:00    False
2020-05-20 13:00:00    False
2020-05-20 14:00:00    False
2020-05-20 15:00:00    False
2020-05-20 16:00:00    False
2020-05-20 17:00:00    False
2020-05-20 18:00:00    False
2020-05-20 19:00:00    False
2020-05-20 20:00:00    False
2020-05-20 21:00:00    False
2020-05-20 22:00:00    False
2020-05-20 23:00:00    False
2020-05-21 00:00:00    False
2020-05-21 01:00:00    False
2020-05-21 02:00:00    False
2020-05-21 03:00:00    False
2020-05-21 04:00:00    False
2020-05-21 05:00:00    False
2020-05-21 06:00:00    False
2020-05-21 07:00:00    False
2020-05-21 08:00:00    False
2020-05-21 09:00:00    False
2020-05-21 10:00:00    False
2020-05-21 11:00:00    False
2020-05-21 12:00:00    False
2020-05-21 13:00:00    False
2020-05-21 14:00:00    False
2020-05-21 15:00:00    False
2020-05-21 16:00:00    False
2020-05-21 17:00:00    False
                       ...
2020-08-10 15:00:00    False
2020-08-10 16:00:00    False
2020-08-10 17:00:00    False
2020-08-10 18:00:00    False
2020-08-10 19:00:00    False
2020-08-10 20:00:00    False
2020-08-10 21:00:00    False
2020-08-10 22:00:00    False
2020-08-10 23:00:00    False
2020-08-11 00:00:00    False
2020-08-11 01:00:00    False
2020-08-11 02:00:00    False
2020-08-11 03:00:00    False
2020-08-11 04:00:00    False
2020-08-11 05:00:00    False
2020-08-11 06:00:00    False
2020-08-11 07:00:00    False
2020-08-11 08:00:00    False
2020-08-11 09:00:00    False
2020-08-11 10:00:00    False
2020-08-11 11:00:00    False
2020-08-11 12:00:00    False
2020-08-11 13:00:00    False
2020-08-11 14:00:00    False
2020-08-11 15:00:00    False
2020-08-11 16:00:00    False
2020-08-11 17:00:00    False
2020-08-11 18:00:00    False
2020-08-11 19:00:00    False
2020-08-11 20:00:00    False
Name: analysis_page_views, Length: 2001, dtype: bool

In [59]:
social_df.drop(columns=['analysis_page_views', 'charts_page_views', 'code_repo_closed_issues', 'code_repo_closed_pull_issues', 'code_repo_contributors', 'code_repo_forks', 'code_repo_open_issues', 'code_repo_open_pull_issues', 'code_repo_stars', 'code_repo_subscribers'], inplace = True)

In [61]:
social_df['twitter_lists'].value_counts()

6631    2001
Name: twitter_lists, dtype: int64

In [65]:
social_df['posts']

time
2020-05-20 12:00:00    119101
2020-05-20 13:00:00    119102
2020-05-20 14:00:00    119106
2020-05-20 15:00:00    119110
2020-05-20 16:00:00    119116
2020-05-20 17:00:00    119131
2020-05-20 18:00:00    119141
2020-05-20 19:00:00    119142
2020-05-20 20:00:00    119144
2020-05-20 21:00:00    119145
2020-05-20 22:00:00    119146
2020-05-20 23:00:00    119146
2020-05-21 00:00:00    119147
2020-05-21 01:00:00    119147
2020-05-21 02:00:00    119148
2020-05-21 03:00:00    119149
2020-05-21 04:00:00    119149
2020-05-21 05:00:00    119149
2020-05-21 06:00:00    119152
2020-05-21 07:00:00    119152
2020-05-21 08:00:00    119153
2020-05-21 09:00:00    119155
2020-05-21 10:00:00    119160
2020-05-21 11:00:00    119165
2020-05-21 12:00:00    119167
2020-05-21 13:00:00    119168
2020-05-21 14:00:00    119168
2020-05-21 15:00:00    119175
2020-05-21 16:00:00    119179
2020-05-21 17:00:00    119180
                        ...
2020-08-10 15:00:00    121629
2020-08-10 16:00:00    121632
2020-08-10 17:00:00    121636
2020-08-10 18:00:00    121639
2020-08-10 19:00:00    121639
2020-08-10 20:00:00    121641
2020-08-10 21:00:00    121644
2020-08-10 22:00:00    121644
2020-08-10 23:00:00    121644
2020-08-11 00:00:00    121645
2020-08-11 01:00:00    121645
2020-08-11 02:00:00    121646
2020-08-11 03:00:00    121647
2020-08-11 04:00:00    121647
2020-08-11 05:00:00    121648
2020-08-11 06:00:00    121649
2020-08-11 07:00:00    121650
2020-08-11 08:00:00    121651
2020-08-11 09:00:00    121649
2020-08-11 10:00:00    121649
2020-08-11 11:00:00    121650
2020-08-11 12:00:00    121652
2020-08-11 13:00:00    121658
2020-08-11 14:00:00    121659
2020-08-11 15:00:00    121661
2020-08-11 16:00:00    121666
2020-08-11 17:00:00    121672
2020-08-11 18:00:00    121681
2020-08-11 19:00:00    121685
2020-08-11 20:00:00    121685
Name: posts, Length: 2001, dtype: int64